### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by noskovvkirill** [vercel/edge-config#95] opened 2023-04-24 05:43 UTC
Hi! We are experiencing an issue in the remote deployment (everything works great locally).
```
### Error in config/get.ts Error: @vercel/edge-config: Network error
    at (node_modules/.pnpm/@vercel+edge-config@0.1.7/node_modules/@vercel/edge-config/dist/index.edge.js:1:1102)
    at (pages/api/config/get.ts:33:24)
    at (node_modules/.pnpm/next@13.3.0_@babel+core@7.21.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/adapter.js:103:0)
```
It happens on any interaction with the edge config client. Env. variables are configured correctly, they were connected through Vercel dashboard.

Thanks!

**Comment by noskovvkirill** [comment] 2023-04-24 15:47
@dferber90 This is how our get.ts looks like
```
import { NextRequest, NextResponse } from 'next/server';
import { parseConnectionString } from '@vercel/edge-config';
import { userFlags } from 'constants/experimental-flags';
import { z } from 'zod';
import { edgeConfig, edgeConfigWhitelist } from 'src/utils/edge-config';
import cors from 'src/utils/cors';

export const config = {
  runtime: 'edge',
};

const handler = async (req: NextRequest) => {
  const { searchParams } = new URL(req.url);
  const userId_ = searchParams.get('userId');
  const userIdValidated = z.string().uuid().safeParse(userId_);
  if (!userIdValidated.success) {
    return NextResponse.json({
      error: 'Invalid "userId" query parameter',
    });
  }
  const userId = userIdValidated.data;
  const connectionString = parseConnectionString(process.env.EDGE_CONFIG!);
  if (!connectionString) {
    throw new Error(
      'Could not parse connection string stored in EDGE_CONFIG environment variable',
    );
  }
  // check if whitelisted
  const whitelisted = await edgeConfigWhitelist.has(userId);

  if (!whitelisted) {
    return cors(
      req,
      NextResponse.json({
        error: 'User is not whitelisted',
      }),
    );
  }

  const value = await edgeConfig.get(userId);
  const flagsValidate = userFlags.safeParse(value);

  if (!flagsValidate.success) {
    return cors(
      req,
      NextResponse.json({
        error: 'User has no flags',
      }),
    );
  }
  return cors(
    req,
    NextResponse.json({
      value: flagsValidate.data || {},
    }),
  );
};

export default handler;

```

src/utils/cors is copied from https://github.com/vercel/examples/blob/main/edge-functions/cors/pages/api/hello.ts

I will try to reproduce it outside of our project today and follow up soon.

**Comment by dferber90** [comment] 2023-04-24 16:50
Could you share the source of `src/utils/edge-config` as well?

**Comment by noskovvkirill** [comment] 2023-04-24 16:52
@dferber90 sure! There it is 
```
import { createClient } from '@vercel/edge-config';

if (!process.env.EDGE_CONFIG) {
  throw new Error('EDGE_CONFIG environment variable is not set');
}

if (!process.env.EDGE_CONFIG_WHITELIST) {
  throw new Error('EDGE_CONFIG_WHITELIST environment variable is not set');
}

const edgeConfig = createClient(process.env.EDGE_CONFIG);
const edgeConfigWhitelist = createClient(process.env.EDGE_CONFIG_WHITELIST);

export { edgeConfig, edgeConfigWhitelist };

```

**Comment by dferber90** [comment] 2023-04-24 18:08
Thanks, I can reproduce the issue! Looking into it

**Comment by dferber90** [comment] 2023-04-24 19:06
Could you try if `@vercel/edge-config@0.1.8-canary.0` fixes this issue for you?

**Comment by dferber90** [comment] 2023-04-25 15:00
Closing as I'm pretty sure this was the reason. Let me know in case you experience it again

**Closed by dferber90** 2023-04-25 15:00 UTC

**Comment by noskovvkirill** [comment] 2023-04-25 16:26
@dferber90 Just tested it! It works now! Appreciate the quick fix!

**Comment by danielbichuetti** [comment] 2024-01-27 18:18
@dferber90 We're having this problem when using Nuxt. Is there any progress being made in the correction of these types of errors?

**Comment by dferber90** [comment] 2024-01-27 18:55
@danielbichuetti The current release (v0.4.1) has a generic catch-all which wrongly resurfaces any caught errors as "Network error", so the actual error you are experiencing might not be a network error. 

We are nearing the v1 release of the Edge Config SDK. Could you try out `@vercel/edge-config@1.0.0-5a12e132-20240123110709` and see if this produces a different error for you or potentially even no error at all?
